apiVersion: apps/v1
kind: Deployment
metadata:
  name: routing-service-demo
  namespace: routing-service

spec:
  replicas: 1
  selector:
    matchLabels:
      routing-config: berlin-new-car
  template:
    metadata:
      labels:
        app: routing-server
        routing-config: berlin-new-car

    spec:
      containers:
      - name: routing-service-car-berlin
        image: tuesd4y/osrm-backend-eks:latest
        env: 
        - name: OSRM_DATA_LABEL
          value: "berlin-new"
        - name: OSRM_MODE
          value: "LOAD"
        - name: OSRM_S3_BUCKET
          value: "s3://triply-routing-data"
          # todo-Chris -> we should use secrets for this instead of storing them in plain text, as outlined in https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables
        - name: OSRM_AWS_ACCESS_KEY_ID
          value: "AKIAY6JW2ISLQO7FBYOE"
        - name: OSRM_AWS_SECRET_ACCESS_KEY
          value: "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"
---
apiVersion: v1
kind: Service
metadata:
  name: routing-service-entrypoint
  namespace: routing-service
  labels:
    app: routing-server
    routing-config: berlin-new-car
  annotations: 
    source-url: "http://download.geofabrik.de/europe/germany/berlin-latest.osm.pbf"
    region: berlin-new
    mode: car
    time: "2022-01-08"
spec:
  type: ClusterIP
  selector:
    routing-config: berlin-new-car
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000